### ISSUE TITLE
Consider DynamicUser= instead of User=

### ISSUE THREAD

**Issue by hairmare** [radiorabe/centos-rpm-rotter#1]
Have you considered using [`DynamicUser=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=) instead of `User=`?

This might be one of the cases where a transient user makes just as much (if not more) sense than using this:

https://github.com/radiorabe/centos-rpm-rotter/blob/ed1d7bf52f10a431b38c81d4d6f4ec0163f1ad27/rotter.spec#L108-L112

I'm assuming that the recording will get chowned when we move the to our storage anyway.

**Comment by paraenggu** [comment]
> Have you considered using `DynamicUser=` instead of `User=`?

Yes I did, but came to the conclusion that it doesn't suite really well here. The service generates files which must be able to persist over a long time and/or over reboots/service restarts. They must be owned by the same user and group, so that `rotter` can delete old files later on (in case it was started with `-d <hours>`) Apart from that, there might (and are in our case) other services which need access to the files and depend on static UID/GIDs to do that. Last but not least, the [D-Bus configuration also depends on the group](https://github.com/radiorabe/centos-rpm-rotter/blob/f2962ae62793d38751ecc01a9ea6bd5614bd05ce/dbus-rotter.conf#L9-L11) to allow access.  This seems to be in line with the recommendations from the  [`DynamicUser=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=) documentation:
> [...] However, UID/GIDs are recycled after a unit is terminated. Care should be taken that any processes running as part of a unit for which dynamic users/groups are enabled do not leave files or directories owned by these users/groups around, as a different unit might get the same UID/GID assigned later on [...]

`DynamicUser=` is a really nice feature, but I see its usage more for services which don't generate persistent data on the filesystem (or only temporary files), such as calling a web API or that like.
